### ISSUE TITLE
How to use rsi_attestation_token_continue

### ISSUE THREAD

**Issue by Bercoke** [TF-RMM/tf-rmm#26]
The memory allocated using kmalloc in the directories linux/arch/arm64/kvm and linux/arch/arm64/kernel fails the memory check performed by rsi_attestation_token_continue.

Memory detection is shown in the figure
![A %)IHJ}2XTDF$F~%AS SVV](https://github.com/TF-RMM/tf-rmm/assets/101735314/33bf101f-268a-4efd-a106-0d80194a542d)

I would like to know where to call the memory allocation function to obtain memory addresses that can pass the memory check.

**Comment by suzukikp** [comment]
Please could you share the calls made by your Linux code ? Are you passing the "PA" of the memory to the RSI call ? 
We have hooked the attestation calls to the Generic COCO TSM CONFIG framework. The patch could be found here :



https://gitlab.arm.com/linux-arm/linux-cca/-/commit/7e5aabb8d7d03f5afcb7224b892eb646ccea91df#7eda40b94a7a616d2ddfd3e218f2632a9e023163_0_76

**Comment by soby-mathew** [comment]
Please feel to reopen if you still have queries on this issue.
