### ISSUE TITLE
RMM is not considering sctlr2_el1.ease when injecting SEA

### ISSUE THREAD

**Issue by soby-mathew** [TF-RMM/tf-rmm#33]
The current TF-RMM code always injects External abort to sync exception vector offset. But when sctlr2_el1.ease is set, TF-RMM needs to inject to SError vector offset.

**Comment by javieralso-arm** [comment]
Patch ready for review at https://review.trustedfirmware.org/c/TF-RMM/tf-rmm/+/31771
