### ISSUE TITLE
#use tag tf-rmm-v0.1.0/tf-rmm-v0.2.0/tf-rmm-v0.3.0, Configure Stage error

### ISSUE THREAD

**Issue by Lee-robbie** [TF-RMM/tf-rmm#6]
when i checkout the tf-rmm to v0.1.0\0.2.0\0.3.0 tag, use the command(cmake -DRMM_CONFIG=fvp_defcfg -S ../tf-rmm/ -B ./build), always report this error, how can i solve it?
-- The C compiler identification is GNU 10.3.1
-- The CXX compiler identification is GNU 10.3.1
-- The ASM compiler identification is GNU
-- Found assembler: /data1/lijunbin/gcc-arm-10.3-2021.07-x86_64-aarch64-none-elf/bin/aarch64-none-elf-gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /data1/lijunbin/gcc-arm-10.3-2021.07-x86_64-aarch64-none-elf/bin/aarch64-none-elf-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /data1/lijunbin/gcc-arm-10.3-2021.07-x86_64-aarch64-none-elf/bin/aarch64-none-elf-c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.25.1")
-- Found Python3: /usr/bin/python3.8 (found version "3.8.10") found components: Interpreter
-- Performing Test C_COMPILER_SUPPORTS_WFORMAT_SIGNEDNESS
-- Performing Test C_COMPILER_SUPPORTS_WFORMAT_SIGNEDNESS - Success
-- Configuring done
CMake Error at lib/t_cose/CMakeLists.txt:6 (add_library):
  Cannot find source file:

    /data1/lijunbin/tf-rmm/ext/t_cose/crypto_adapters/t_cose_mbedtls_crypto.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at lib/t_cose/CMakeLists.txt:6 (add_library):
  No SOURCES given to target: t_cose

**Comment by soby-mathew** [comment]
Similar issue to https://github.com/TF-RMM/tf-rmm/issues/5 .
